sudo: false
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
matrix:
  include:
  - python: 3.7
    env: TOXENV=pep8
    dist: xenial
    sudo: true
  - python: 2.7
    env: TOXENV=py27
  - python: 3.7
    env: TOXENV=py37
    dist: xenial
    sudo: true
  - python: 3.7
    dist: xenial
    sudo: true
    script: skip  # Skipping as tests are executed prior to hitting this stage
    if: tag =~ ^v
    deploy:
      provider: pypi
      user: jimbobhickville
      password:
        secure: "F4DpoTcqXkKvQZ3zNJS/3p8107s/TkdVd0+Pd2xw2jFiZNNyWq7tJftQMRJdD2toDLYiqnTUpIsYwLblvrnVmhHQtF9EitImjbPP+D0q1bqzfue2hHnmU2BxFkne+pP9yY3/ORAy6nuPbo4POlTt0/aOx6WifFy2kqlD45OOfcN4+8gLjuZlWdZfugCLXdx3oZOQqhFqWfwqxbcdXkZchrvMVUrH6wyCSXtyPu6HUU6r5aJSO4sCfPLoMhRwRvQNqqhq7vuCJHMWwkjMx5YCzD7+7H+1MFo6/L3p8PbUmAtnPD5+PD3lLqANqSHBqE69gCZF7WiJO1C7Qs7NuoqE9MU+xT3qfsdfkq/7zW0ckNkcx499jBeBHk/OnvwQwvIPXLrH9bJgtFAZDyqEb3p+8zY13i9x7EfDQEl67baT1l7FxaupDp1mGaBeswXSe68eGL2nReRndEnY4KcHrPN8kDzql2JnNf2OF0fYZTqUxrPYEGA+2hgDZYDgYY7GA2t0X5Nwp43ZyyHiD9fB5a/n60FhBlWb82//X0DuOg9LBzKtjg8kSI+iYImXqlBaLWRTd5YWAqvmL1jC3JpvQyLa2qlaxFT/bJBhHQoEoFSs0awGRQ6QkfLGRCZrrIl9qNTDElMJa9maldrC/1Z+sh9ftSE57IST9EuzST/JDa1Ima8="
      distributions: "sdist bdist_wheel"
      on:
        tags: true

install:
- pip install tox
script:
- tox -e $TOXENV
